"""Add Group model

Revision ID: 04b19c7c673c
Revises: 8197f57195c3
Create Date: 2025-01-20 12:51:45.264171

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04b19c7c673c"
down_revision: Union[str, None] = "8197f57195c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("list", sa.Column("group_id", sa.Integer(), nullable=True))
    with op.batch_alter_table("list", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_list_group", "group", ["group_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("list", schema=None) as batch_op:
        batch_op.drop_constraint("fk_list_group", type_="foreignkey")
    op.drop_column("list", "group_id")
    op.drop_table("group")
    # ### end Alembic commands ###
