"""Add missing indexes

Revision ID: 90e89bcc20a0
Revises: 645828e981e2
Create Date: 2025-01-07 08:19:51.379365

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90e89bcc20a0"
down_revision: Union[str, None] = "645828e981e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_due_date", table_name="task")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_task_due_date", "task", ["due_date"], unique=False)
    # ### end Alembic commands ###
